import { useCallback, useEffect, useRef, useState } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import { Loader2, MessageSquare } from 'lucide-react'

import { Button } from '@ds/v3-components/Button/Button'
import { MessageBubble } from '@ds/v3-components/MessageBubble/MessageBubble'
import { Textarea } from '@ds/v3-components/Textarea/Textarea'

import { useAppStore, visibleDeployments } from '../store/useAppStore.js'
import { serverFetch } from '../lib/api.js'
import { serviceDetailPath } from '../lib/routes.js'
import { getAssistantModel } from '../lib/assistant/aiModel.js'
import { AssistantMarkdown } from './AssistantMarkdown.jsx'
import { readTriageSseStream } from '../lib/assistant/parseStream.js'
import { gatherServiceDiagnostics } from '../lib/assistant/diagnostics.js'
import { buildAssistantContext } from '../lib/assistant/buildContext.js'
import { parseScaleAction } from '../lib/assistant/deployPreview.js'

/* eslint-disable @typescript-eslint/no-explicit-any */

const PLACEHOLDER = 'Ask about your services, or describe what you want to deploy...'

function newMsgId() {
  if (typeof crypto !== 'undefined' && crypto.randomUUID) return crypto.randomUUID()
  return 'm-' + Date.now() + '-' + Math.random().toString(16).slice(2)
}

interface ChatAction {
  label: string
  secondary?: boolean
  onClick: () => void
}

interface ChatRow {
  id: string
  role: 'user' | 'assistant'
  text: string
  userDisplay?: string
  stream?: boolean
  isMd?: boolean
  actions?: ChatAction[]
}

export function AssistantPanel({ open, onClose }: { open: boolean; onClose: () => void }) {
  const location = useLocation()
  const navigate = useNavigate()
  const token = useAppStore((s) => s.token)
  const [input, setInput] = useState('')
  const [sending, setSending] = useState(false)
  const [rows, setRows] = useState<ChatRow[]>([])
  const [thinking, setThinking] = useState<null | { phase: 'fetch' | 'analyse'; name?: string }>(
    null,
  )
  const inputRef = useRef<HTMLTextAreaElement>(null)
  const scrollRef = useRef<HTMLDivElement>(null)
  const historyRef = useRef<Array<{ role: string; content: string }>>([])
  const sendingRef = useRef(false)

  const scrollToBottom = useCallback(() => {
    const el = scrollRef.current
    if (el) el.scrollTop = el.scrollHeight
  }, [])

  useEffect(() => {
    if (open) {
      setTimeout(() => inputRef.current?.focus(), 200)
    }
  }, [open])

  useEffect(() => {
    scrollToBottom()
  }, [rows, thinking, open, scrollToBottom])

  const addUser = useCallback((text: string, userDisplay?: string) => {
    setRows((r) => [
      ...r,
      { id: newMsgId(), role: 'user', text, userDisplay: userDisplay || text },
    ])
  }, [])

  const sendChat = useCallback(async () => {
    const text = input.trim()
    if (!text || sendingRef.current) return
    sendingRef.current = true
    setSending(true)
    setInput('')

    addUser(text, text)
    historyRef.current = [...historyRef.current, { role: 'user', content: text }]

    setThinking({ phase: 'analyse' })
    const ctx = buildAssistantContext(location.pathname)
    const lowerText = text.toLowerCase()
    const isScaleQ = /scale\s+[\w-]+\s+(?:(?:down|up)\s+to|to)\s+\d+/i.test(lowerText)
    const isHealthQ =
      !isScaleQ &&
      /(health|status|slow|broken|error|crash|fail|issue|problem|check|investigat|triage|log|metric|event)/i.test(
        lowerText,
      )

    let diagnosticData = ''
    const deps = visibleDeployments(useAppStore.getState())
    const segs = location.pathname.split('/').filter(Boolean)
    const fromRoute =
      segs[0] === 'applications' && segs.length >= 4
        ? deps.find(
            (d: any) =>
              d.metadata.name === segs[3] &&
              d.metadata.namespace === segs[2] &&
              String(d._envId) === String(segs[1]),
          )
        : null
    if (isHealthQ) {
      const targetDep =
        deps.find((d: any) => lowerText.includes(d.metadata.name.toLowerCase())) || fromRoute
      if (targetDep) {
        setThinking({ phase: 'fetch', name: targetDep.metadata.name })
        try {
          diagnosticData = await gatherServiceDiagnostics(token, targetDep)
        } catch {
          /* */
        }
        setThinking({ phase: 'analyse' })
      }
    }

    const diagnosticNote = diagnosticData
      ? 'LIVE DIAGNOSTIC DATA IS PROVIDED BELOW. You have direct access to the logs, events, and pod status. Analyse them and answer immediately. Do NOT say you lack access or ask the user to check anything themselves.'
      : ''
    const deployFeatures =
      '- Deploy: drop source files generated by an AI coding tool (Node, Python, Ruby, PHP, static HTML). Runtime is detected automatically, dependencies are installed, and the app is deployed via GitOps. This is the only deployment method on this instance.'

    const deployInstructions = `IMPORTANT RULES:
- If the user asks to deploy ANYTHING — an app, a service, wordpress, anything — do NOT attempt to generate a deployment config, search for docker-compose files, or suggest container images. Deploy is the only deployment method available on this instance.
- Instead, respond with this exact message: "To deploy an app here, use an AI coding tool (like Claude) to build your application, then go to **Deploy** and upload the generated files — Portainer-Run handles the rest automatically."
- If the user asks what Deploy is or how it works, explain: it accepts source files (Node.js, Python, Ruby, PHP, or static HTML) generated by AI coding tools, detects the runtime automatically, installs dependencies, and deploys to Kubernetes via GitOps.
- If the user asks about scaling, health, logs, or status of existing services, answer normally.
- Never suggest using docker-compose, container images, or any other deployment method — they are not available.`

    const systemPrompt = `You are the built-in assistant for Portainer-Run — a lightweight Internal Developer Portal (IDP) for Kubernetes, backed by Portainer. You help users deploy, manage, and troubleshoot containerised applications.

${diagnosticNote}

Portainer-Run OVERVIEW:
- All deployments go through GitOps. Portainer-Run generates Kubernetes manifests, commits them to a user-configured Git target, and Portainer deploys via a GitOps stack that polls the repository for changes.
${deployFeatures}
- Git Targets: repositories where manifests are committed. Each deployment references its own Git target. Credentials stored encrypted server-side.
- Applications page: lists all deployments tagged managed-by=portainer-run. Shows status, replicas, exposure, and age.
- Editing a running application commits an updated manifest to Git — Portainer reconciles automatically on the next poll cycle.

SCOPE: Only answer questions about container operations, deployments, Kubernetes workloads, logs, metrics, application health, and Portainer-Run features. Politely decline anything outside this scope.

Session context: ${ctx}${diagnosticData}

${deployInstructions}`

    const messages = diagnosticData
      ? historyRef.current.slice(-2)
      : historyRef.current.slice(-10)

    const assistantId = newMsgId()
    setRows((r) => [
      ...r,
      { id: assistantId, role: 'assistant', text: '', stream: true, isMd: true },
    ])
    setThinking(null)

    try {
      const response = await serverFetch('/ai/triage', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          model: getAssistantModel(),
          max_tokens: 1500,
          stream: true,
          system: systemPrompt,
          messages,
        }),
      })
      if (!response.ok) {
        let eb: any = {}
        try {
          eb = await response.json()
        } catch {
          /* */
        }
        const err = eb?.error
        const emsg = typeof err === 'string' ? err : err?.message || 'HTTP ' + response.status
        throw new Error(emsg)
      }

      const fullText = await readTriageSseStream(response.body, (acc: string) => {
        setRows((r) =>
          r.map((row) =>
            row.id === assistantId ? { ...row, text: acc, isMd: true, stream: true } : row,
          ),
        )
      })

      {
        const scale = parseScaleAction(fullText)
        setRows((r) =>
          r.map((row) =>
            row.id === assistantId
              ? {
                  ...row,
                  text: fullText,
                  isMd: true,
                  stream: false,
                  actions: scale
                    ? [
                        {
                          label: `Open Edit tab for ${scale.serviceName}`,
                          secondary: false,
                          onClick: () => {
                            navigate(
                              serviceDetailPath(
                                scale.envId,
                                scale.namespace,
                                scale.serviceName,
                                'edit',
                              ),
                              { state: { assistantPrefillInstances: scale.instances } },
                            )
                            setRows((x) => [
                              ...x,
                              {
                                id: newMsgId(),
                                role: 'assistant',
                                text: `Opened the Edit tab for **${scale.serviceName}**. Instances set to **${scale.instances}**. Save when ready.`,
                                isMd: true,
                              },
                            ])
                          },
                        },
                      ]
                    : undefined,
                }
              : row,
          ),
        )
      }
      historyRef.current = [...historyRef.current, { role: 'assistant', content: fullText }]
    } catch (e: any) {
      setRows((r) =>
        r.map((row) =>
          row.id === assistantId
            ? { ...row, text: 'Sorry, I ran into an error: ' + (e?.message || 'Unknown') }
            : row,
        ),
      )
    } finally {
      sendingRef.current = false
      setSending(false)
    }
  }, [addUser, input, location.pathname, navigate, token])

  const onKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault()
      void sendChat()
    }
  }

  if (!open) return null

  return (
    <div
      role="complementary"
      aria-label="Assistant"
      style={{
        display: 'flex',
        flexDirection: 'column',
        position: 'fixed',
        top: 0,
        right: 0,
        width: 360,
        height: '100vh',
        zIndex: 9999,
        background: 'var(--content-bg, var(--bg))',
        borderLeft: '1px solid var(--border)',
        boxShadow: '-4px 0 20px rgba(0,0,0,0.25)',
        overflow: 'hidden',
      }}
    >
      {/* Header */}
      <div
        style={{
          display: 'flex',
          alignItems: 'center',
          gap: 8,
          padding: '14px 16px',
          borderBottom: '1px solid var(--border)',
          flexShrink: 0,
        }}
      >
        <span style={{ fontSize: 13, fontWeight: 600, color: 'var(--text)' }}>Assistant</span>
        <div style={{ flex: 1 }} />
        <Button variant="ghost" size="sm" onClick={onClose} title="Close panel">
          Close
        </Button>
      </div>

      {/* Input (kept above the messages, as in the original layout) */}
      <div
        style={{
          display: 'flex',
          flexDirection: 'column',
          gap: 8,
          padding: '12px 14px',
          borderBottom: '1px solid var(--border)',
          flexShrink: 0,
        }}
      >
        <Textarea
          ref={inputRef}
          rows={4}
          placeholder={PLACEHOLDER}
          value={input}
          onChange={(e) => setInput(e.target.value)}
          onKeyDown={onKeyDown}
          disabled={sending}
          fieldSize="sm"
        />
        <Button
          size="sm"
          style={{ alignSelf: 'flex-end' }}
          onClick={() => void sendChat()}
          disabled={sending || !input.trim()}
        >
          Send
        </Button>
      </div>

      {/* Messages */}
      <div
        ref={scrollRef}
        style={{
          flex: 1,
          overflowY: 'auto',
          overflowX: 'hidden',
          padding: '12px 14px',
          display: 'flex',
          flexDirection: 'column',
          gap: 10,
        }}
      >
        {rows.length === 0 && !thinking && (
          <div
            style={{
              display: 'flex',
              flexDirection: 'column',
              alignItems: 'center',
              justifyContent: 'center',
              height: '100%',
              opacity: 0.6,
            }}
          >
            <MessageSquare size={24} style={{ opacity: 0.3, marginBottom: 8 }} />
            <div
              style={{
                fontSize: 12,
                color: 'var(--muted)',
                lineHeight: 1.6,
                textAlign: 'center',
              }}
            >
              Ask about your services or describe what you want to deploy.
            </div>
          </div>
        )}
        {rows.map((row) => {
          if (row.role === 'user') {
            return (
              <MessageBubble key={row.id} role="user">
                {String(row.userDisplay ?? row.text ?? '')}
              </MessageBubble>
            )
          }
          return (
            <MessageBubble key={row.id} role="assistant" streaming={row.stream}>
              {row.isMd ? (
                <div style={{ minHeight: 8 }}>
                  <AssistantMarkdown>{row.text || (row.stream ? '…' : '—')}</AssistantMarkdown>
                </div>
              ) : (
                <span style={{ whiteSpace: 'pre-wrap' }}>{row.text}</span>
              )}
              {row.actions && row.actions.length > 0 ? (
                <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap', marginTop: 10 }}>
                  {row.actions.map((a) => (
                    <Button
                      key={a.label}
                      variant={a.secondary ? 'ghost' : 'light'}
                      size="xs"
                      onClick={a.onClick}
                    >
                      {a.label}
                    </Button>
                  ))}
                </div>
              ) : null}
            </MessageBubble>
          )
        })}
        {thinking && (
          <div
            style={{
              alignSelf: 'flex-start',
              display: 'flex',
              alignItems: 'center',
              gap: 8,
              fontSize: 12,
              color: 'var(--muted)',
            }}
          >
            <Loader2 size={11} className="animate-spin" />
            {thinking.phase === 'fetch'
              ? 'Fetching diagnostics for ' + (thinking.name || 'application') + '...'
              : 'Analysing...'}
          </div>
        )}
      </div>
    </div>
  )
}
