import { useCallback, useEffect, useRef, useState } from 'react'
import { useLocation, useNavigate } from 'react-router-dom'
import { useAppStore, visibleDeployments } from '../store/useAppStore.js'
import { serviceDetailPath } from '../lib/routes.js'
import { getAssistantModel } from '../lib/assistant/aiModel.js'
import { mdToHtml } from '../lib/assistant/markdown.js'
import { readTriageSseStream } from '../lib/assistant/parseStream.js'
import { gatherServiceDiagnostics } from '../lib/assistant/diagnostics.js'
import { buildAssistantContext } from '../lib/assistant/buildContext.js'
import { parseScaleAction } from '../lib/assistant/deployPreview.js'

const PLACEHOLDER =
  'Ask about your services, or describe what you want to deploy...'

function newMsgId() {
  if (typeof crypto !== 'undefined' && crypto.randomUUID) return crypto.randomUUID()
  return 'm-' + Date.now() + '-' + Math.random().toString(16).slice(2)
}

/**
 * @param {object} props
 * @param {boolean} props.open
 * @param {() => void} props.onClose
 */
export function AssistantPanel({ open, onClose }) {
  const location = useLocation()
  const navigate = useNavigate()
  const token = useAppStore((s) => s.token)
  const [input, setInput] = useState('')
  const [sending, setSending] = useState(false)
  const [rows, setRows] = useState(/** @type {Array<Record<string, unknown>>} */ ([]))
  const [thinking, setThinking] = useState(
    /** @type {null | { phase: 'fetch' | 'analyse', name?: string }} */ (null),
  )
  const inputRef = useRef(null)
  const scrollRef = useRef(null)
  const historyRef = useRef(/** @type {Array<{ role: string, content: string }>} */ ([]))
  const sendingRef = useRef(false)

  const scrollToBottom = useCallback(() => {
    const el = scrollRef.current
    if (el) el.scrollTop = el.scrollHeight
  }, [])

  useEffect(() => {
    if (open) {
      setTimeout(() => inputRef.current?.focus(), 200)
    }
  }, [open])

  useEffect(() => {
    scrollToBottom()
  }, [rows, thinking, open, scrollToBottom])

  const addUser = useCallback((text, userDisplay) => {
    setRows((r) => [
      ...r,
      { id: newMsgId(), role: 'user', text, userDisplay: userDisplay || text },
    ])
  }, [])

  const addError = useCallback((msg) => {
    setRows((r) => [...r, { id: newMsgId(), role: 'assistant', text: msg }])
  }, [])

  const sendChat = useCallback(async () => {
    const text = input.trim()
    if (!text || sendingRef.current) return
    sendingRef.current = true
    setSending(true)
    setInput('')

    addUser(text, text)
    historyRef.current = [...historyRef.current, { role: 'user', content: text }]

    setThinking({ phase: 'analyse' })
    const ctx = buildAssistantContext(location.pathname)
    const lowerText = text.toLowerCase()
    const isScaleQ = /scale\s+[\w-]+\s+(?:(?:down|up)\s+to|to)\s+\d+/i.test(lowerText)
    const isHealthQ =
      !isScaleQ &&
      /(health|status|slow|broken|error|crash|fail|issue|problem|check|investigat|triage|log|metric|event)/i.test(
        lowerText,
      )

    let diagnosticData = ''
    const deps = visibleDeployments(useAppStore.getState())
    const segs = location.pathname.split('/').filter(Boolean)
    const fromRoute =
      segs[0] === 'applications' && segs.length >= 4
        ? deps.find(
            (d) =>
              d.metadata.name === segs[3] &&
              d.metadata.namespace === segs[2] &&
              String(d._envId) === String(segs[1]),
          )
        : null
    if (isHealthQ) {
      const targetDep =
        deps.find((d) => lowerText.includes(d.metadata.name.toLowerCase())) || fromRoute
      if (targetDep) {
        setThinking({ phase: 'fetch', name: targetDep.metadata.name })
        try {
          diagnosticData = await gatherServiceDiagnostics(token, targetDep)
        } catch {
          /* */
        }
        setThinking({ phase: 'analyse' })
      }
    }

    const diagnosticNote = diagnosticData
      ? 'LIVE DIAGNOSTIC DATA IS PROVIDED BELOW. You have direct access to the logs, events, and pod status. Analyse them and answer immediately. Do NOT say you lack access or ask the user to check anything themselves.'
      : ''
    const deployFeatures =
      '- Deploy: drop source files generated by an AI coding tool (Node, Python, Ruby, PHP, static HTML). Runtime is detected automatically, dependencies are installed, and the app is deployed via GitOps. This is the only deployment method on this instance.'

    const deployInstructions = `IMPORTANT RULES:
- If the user asks to deploy ANYTHING — an app, a service, wordpress, anything — do NOT attempt to generate a deployment config, search for docker-compose files, or suggest container images. Deploy is the only deployment method available on this instance.
- Instead, respond with this exact message: "To deploy an app here, use an AI coding tool (like Claude) to build your application, then go to **Deploy** and upload the generated files — Portainer-Run handles the rest automatically."
- If the user asks what Deploy is or how it works, explain: it accepts source files (Node.js, Python, Ruby, PHP, or static HTML) generated by AI coding tools, detects the runtime automatically, installs dependencies, and deploys to Kubernetes via GitOps.
- If the user asks about scaling, health, logs, or status of existing services, answer normally.
- Never suggest using docker-compose, container images, or any other deployment method — they are not available.`

    const systemPrompt = `You are the built-in assistant for Portainer-Run — a lightweight Internal Developer Portal (IDP) for Kubernetes, backed by Portainer. You help users deploy, manage, and troubleshoot containerised applications.

${diagnosticNote}

Portainer-Run OVERVIEW:
- All deployments go through GitOps. Portainer-Run generates Kubernetes manifests, commits them to a user-configured Git target, and Portainer deploys via a GitOps stack that polls the repository for changes.
${deployFeatures}
- Git Targets: repositories where manifests are committed. Each deployment references its own Git target. Credentials stored encrypted server-side.
- Applications page: lists all deployments tagged managed-by=portainer-run. Shows status, replicas, exposure, and age.
- Editing a running application commits an updated manifest to Git — Portainer reconciles automatically on the next poll cycle.

SCOPE: Only answer questions about container operations, deployments, Kubernetes workloads, logs, metrics, application health, and Portainer-Run features. Politely decline anything outside this scope.

Session context: ${ctx}${diagnosticData}

${deployInstructions}`

    const messages = diagnosticData
      ? historyRef.current.slice(-2)
      : historyRef.current.slice(-10)

    const assistantId = newMsgId()
    setRows((r) => [...r, { id: assistantId, role: 'assistant', text: '', stream: true, isMd: true }])
    setThinking(null)

    try {
      const response = await fetch('/ai/triage', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          model: getAssistantModel(),
          max_tokens: 1500,
          stream: true,
          system: systemPrompt,
          messages,
        }),
      })
      if (!response.ok) {
        let eb = {}
        try {
          eb = await response.json()
        } catch {
          /* */
        }
        const err = eb?.error
        const emsg = typeof err === 'string' ? err : err?.message || 'HTTP ' + response.status
        throw new Error(emsg)
      }

      const fullText = await readTriageSseStream(response.body, (acc) => {
        setRows((r) =>
          r.map((row) =>
            row.id === assistantId
              ? { ...row, text: acc, isMd: true, stream: true }
              : row,
          ),
        )
      })

      {
        const scale = parseScaleAction(fullText)
        setRows((r) =>
          r.map((row) =>
            row.id === assistantId
              ? {
                  ...row,
                  text: fullText,
                  isMd: true,
                  stream: false,
                  actions: scale
                    ? [
                        {
                          label: `Open Edit tab for ${scale.serviceName}`,
                          secondary: false,
                          onClick: () => {
                            navigate(
                              serviceDetailPath(
                                scale.envId,
                                scale.namespace,
                                scale.serviceName,
                                'edit',
                              ),
                              { state: { assistantPrefillInstances: scale.instances } },
                            )
                            setRows((x) => [
                              ...x,
                              {
                                id: newMsgId(),
                                role: 'assistant',
                                text: `Opened the Edit tab for **${scale.serviceName}**. Instances set to **${scale.instances}**. Save when ready.`,
                                isMd: true,
                              },
                            ])
                          },
                        },
                      ]
                    : undefined,
                }
              : row,
          ),
        )
      }
      historyRef.current = [...historyRef.current, { role: 'assistant', content: fullText }]
    } catch (e) {
      setRows((r) =>
        r.map((row) =>
          row.id === assistantId
            ? { ...row, text: 'Sorry, I ran into an error: ' + (e?.message || 'Unknown') }
            : row,
        ),
      )
    } finally {
      sendingRef.current = false
      setSending(false)
    }
  }, [addError, addUser, input, location.pathname, navigate, token])

  const onKeyDown = (e) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault()
      void sendChat()
    }
  }

  if (!open) return null

  return (
    <div className="chat-panel open" role="complementary" aria-label="Assistant">
      <div className="chat-header">
        <span className="chat-title">Assistant</span>
        <div style={{ flex: 1 }} />
        <button
          type="button"
          className="btn btn-ghost btn-sm"
          onClick={onClose}
          title="Close panel"
        >
          Close
        </button>
      </div>
      <div className="chat-input-wrap">
        <textarea
          ref={inputRef}
          className="chat-input"
          rows={4}
          placeholder={PLACEHOLDER}
          value={input}
          onChange={(e) => setInput(e.target.value)}
          onKeyDown={onKeyDown}
          disabled={sending}
        />
        <button
          type="button"
          className="btn btn-primary btn-sm"
          style={{ alignSelf: 'flex-end' }}
          onClick={() => void sendChat()}
          disabled={sending || !input.trim()}
        >
          Send
        </button>
      </div>
      <div className="chat-messages" ref={scrollRef}>
        {rows.length === 0 && !thinking && (
          <div className="chat-empty">
            <svg
              width="24"
              height="24"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              strokeWidth="1.5"
              style={{ opacity: 0.3, marginBottom: 8 }}
            >
              <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z" />
            </svg>
            <div
              style={{
                fontSize: 12,
                color: 'var(--text-dim)',
                lineHeight: 1.6,
                textAlign: 'center',
              }}
            >
              Ask about your services or describe what you want to deploy.
            </div>
          </div>
        )}
        {rows.map((row) => {
          if (row.role === 'user') {
            return (
              <div key={row.id} className="chat-msg">
                <div className="chat-msg-user">{String(row.userDisplay ?? row.text ?? '')}</div>
              </div>
            )
          }
          return (
            <div key={row.id} className="chat-msg">
              <div className="chat-msg-assistant">
                {row.isMd ? (
                  <div
                    style={{ minHeight: 8 }}
                    dangerouslySetInnerHTML={{ __html: mdToHtml(row.text || (row.stream ? '…' : '—')) }}
                  />
                ) : (
                  <span style={{ whiteSpace: 'pre-wrap' }}>{row.text}</span>
                )}
                {row.actions && row.actions.length > 0 ? (
                  <div
                    className="chat-action-row"
                    style={{ display: 'flex', gap: 8, flexWrap: 'wrap', marginTop: 10 }}
                  >
                    {row.actions.map((a) => (
                      <button
                        type="button"
                        key={a.label}
                        className={'chat-action-btn' + (a.secondary ? ' secondary' : '')}
                        onClick={a.onClick}
                      >
                        {a.label}
                      </button>
                    ))}
                  </div>
                ) : null}
              </div>
            </div>
          )
        })}
        {thinking && (
          <div className="chat-msg" style={{ alignSelf: 'flex-start' }}>
            <div className="chat-thinking">
              <div className="spinner" style={{ width: 10, height: 10, borderWidth: 2 }} />
              {thinking.phase === 'fetch'
                ? 'Fetching diagnostics for ' + (thinking.name || 'application') + '...'
                : 'Analysing...'}
            </div>
          </div>
        )}
      </div>
    </div>
  )
}
